services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
    restart: always
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
    restart: always
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - ./database:/var/lib/mysql
    networks:
      inception:
    restart: always

networks:
  inception:
    name: inception

# to keep the data persistent
# path will be changed according to the host machine
# volumes:
#   mariadb:
#     name: mariadb
#     driver: local
#     driver_opts:
#       device: /home/data/mariadb
#       o: bind
#       type: none
#   wordpress:
#     name: wordpress
#     driver: local
#     driver_opts:
#       device: /home/data/wordpress
#       o: bind
#       type: none
